/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package client.registration

import client.registration.cli.ClientRegistrationMenu;
import client.registration.dto.Client;
import client.registration.repository.DataStore;


class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

data class CLICommand (
    val command: String,
    val fn: () -> Unit,
    val children: List<CLICommand>?
) {
    fun print(preamble: String = " ") {
        println("${preamble}- $command")
        if (children != null) for (command in children) command.print(preamble + "  ")
    }
}

fun startClientRegistrationMenu(preamble: String): Unit {
    println("##### Client Registration Menu #####")
    println("$preamble -> ")
}

val openClientRegistrationMenu = fun () {
    println("THIS IS CLIENT REGISTRATION MENU. WELCOME.")
}

fun buildClientRegistrationMenu() : CLICommand {
    return CLICommand("client", openClientRegistrationMenu, listOf(
            CLICommand("add-client", {
                println("Adding client")
            }, null),
            CLICommand("list-clients",  {
                println("Retrieving all clients")
            }, null)
        )
    )
}

class DataStoreImpl : DataStore {
  override fun save(client: Client) {
    println("New client registered!")
  }
}

fun main() {
    // startClientRegistrationMenu("RentalShop")
    // //var add
    // val clientRegistrationMenu = buildClientRegistrationMenu()
    // clientRegistrationMenu.print()
    val menu = ClientRegistrationMenu(DataStoreImpl());
    val command = menu.buildMenu();
    command.execute();
}
